apiVersion: apps/v1
kind: Deployment
metadata:
  name: targeting-service
  namespace: togglemaster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: targeting-service
  template:
    metadata:
      labels:
        app: targeting-service
    spec:
      containers:
        - name: targeting-service
          image: 923654441009.dkr.ecr.us-east-1.amazonaws.com/tc3-togglemaster-targeting:d3584a6a4cb896a651fe1fc400bb13d72a09cb37
          ports:
            - containerPort: 8003
          env:
            - name: DATABASE_URL
              valueFrom:
                secretKeyRef:
                  name: targeting-service-secret
                  key: DATABASE_URL
            - name: PORT
              valueFrom:
                secretKeyRef:
                  name: targeting-service-secret
                  key: PORT
            - name: AUTH_SERVICE_URL
              valueFrom:
                secretKeyRef:
                  name: targeting-service-secret
                  key: AUTH_SERVICE_URL